# Generated by Django 4.2.8 on 2025-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commission_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_style',
            field=models.CharField(max_length=100),
        ),
    ]
