# Generated by Django 4.2.8 on 2025-06-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_commission_commission_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='completion_date',
            field=models.CharField(default='TBA', max_length=100),
        ),
        migrations.AddField(
            model_name='commission',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reference_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to=settings.AUTH_USER_MODEL)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='api.commission')),
            ],
        ),
    ]
