# Generated by Django 4.2.8 on 2025-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commission_completion_date_commission_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
