# Generated by Django 4.2.8 on 2025-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='kind',
            field=models.CharField(default='', max_length=100),
        ),
    ]
