# Generated by Django 4.2.8 on 2025-06-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_log_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='progress',
            field=models.JSONField(default=dict),
        ),
    ]
