# Generated by Django 4.2.8 on 2025-06-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_commission_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='progress',
        ),
    ]
