# Generated by Django 4.2.8 on 2025-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='status_progress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='progress',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
